from enum import Enum

class GameMode(Enum):
    UNKNOWN = 0
    ALL_PICK= 1
    CAPTAINS_MODE = 2
    RANDOM_DRAFT = 3
    SINGLE_DRAFT = 4
    ALL_RANDOM = 5
    INTRO_DEATH = 6
    THE_DIRETIDE = 7
    REVERSE_CAPTAINS_MODE = 8
    GREEVILING = 9
    TUTORIAL = 10
    MID_ONLY = 11
    LEAST_PLAYED = 12
    LIMITED_HERO = 13
    COMPENDIUM_MATCHMAKING = 14
    CUSTOM = 15
    CAPTAINS_DRAFT = 16
    NEW_BLOOM = 17
    ABILITY_DRAFT = 18
    EVENT = 19
    ARDM = 20
    ONEVONE_MID = 21
    ALL_DRAFT = 22
